.github/workflows
name: Generate Contribution Snake

on:
  # এটি প্রতিদিন UTC রাত 12টায় স্বয়ংক্রিয়ভাবে রান করবে
  schedule:
    - cron: "0 0 * * *" 
  # ম্যানুয়ালি রান করার জন্য
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # SVG জেনারেট করার জন্য Action টি ব্যবহার
      - uses: Platane/snk@v3
        with:
          # আপনার GitHub ইউজারনেম
          github_user_name: CodeWithArafat1 
          # জেনারেটেড ফাইলটি এই লোকেশনে সেভ হবে
          outputs: dist/github-contribution-grid-snake.svg
